import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/closebrackets",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/comment",
        "@codemirror/fold",
        "@codemirror/gutter",
        "@codemirror/highlight",
        "@codemirror/history",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/matchbrackets",
        "@codemirror/panel",
        "@codemirror/rangeset",
        "@codemirror/rectangular-selection",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/stream-parser",
        "@codemirror/text",
        "@codemirror/tooltip",
        "@codemirror/view",
        ...builtins],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
});

import { copyFileSync, mkdirSync, existsSync } from "fs";
import { dirname } from "path";

const targetDir = "/Users/Tadanori/Library/CloudStorage/Dropbox/textbox_node/local/data/.obsidian/plugins/obsidian-link-expander";

if (!existsSync(targetDir)) {
    mkdirSync(targetDir, { recursive: true });
}

const copyFiles = () => {
    copyFileSync("main.js", `${targetDir}/main.js`);
    copyFileSync("manifest.json", `${targetDir}/manifest.json`);
    if (existsSync("styles.css")) {
        copyFileSync("styles.css", `${targetDir}/styles.css`);
    }
};

copyFiles();

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
