/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LinkExpanderPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var LinkExpanderPlugin = class extends import_obsidian.Plugin {
  async onload() {
    this.addCommand({
      id: "open-all-internal-links",
      name: "Open all links in new tabs",
      checkCallback: (checking) => {
        const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (markdownView) {
          if (!checking) {
            this.openAllLinks(markdownView);
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "close-all-linked-tabs",
      name: "Close all linked tabs",
      checkCallback: (checking) => {
        const markdownView = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
        if (markdownView) {
          if (!checking) {
            this.closeAllLinkedTabs(markdownView);
          }
          return true;
        }
        return false;
      }
    });
  }
  async openAllLinks(view) {
    const file = view.file;
    if (!file)
      return;
    const cache = this.app.metadataCache.getFileCache(file);
    if (!cache || !cache.links) {
      console.log("Link Expander: No links found in this note.");
      return;
    }
    console.log(`Link Expander: Found ${cache.links.length} links.`);
    const uniqueLinks = /* @__PURE__ */ new Set();
    cache.links.forEach((link) => {
      uniqueLinks.add(link.link);
    });
    for (const linkPath of uniqueLinks) {
      await this.app.workspace.openLinkText(linkPath, file.path, true);
    }
    this.app.workspace.setActiveLeaf(view.leaf, { focus: true });
  }
  async closeAllLinkedTabs(view) {
    const file = view.file;
    if (!file)
      return;
    const cache = this.app.metadataCache.getFileCache(file);
    if (!cache || !cache.links) {
      console.log("Link Expander: No links found in this note to close.");
      return;
    }
    const uniqueLinks = /* @__PURE__ */ new Set();
    cache.links.forEach((link) => {
      uniqueLinks.add(link.link);
    });
    const leavesToDetach = [];
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (leaf === view.leaf)
        return;
      if (leaf.view instanceof import_obsidian.FileView) {
        const leafFile = leaf.view.file;
        if (leafFile) {
          for (const linkText of uniqueLinks) {
            const targetFile = this.app.metadataCache.getFirstLinkpathDest(linkText, file.path);
            if (targetFile && targetFile.path === leafFile.path) {
              leavesToDetach.push(leaf);
              break;
            }
          }
        }
      }
    });
    leavesToDetach.forEach((leaf) => leaf.detach());
  }
};
